---
- hosts: CSR  # playbook操作的设备
  gather_facts: false  # 并不搜集这些主机的信息
  connection: local  # 本地发起连接
  vars_files:
    - customer_config.yaml  # 导入配置信息文件

  tasks:  # 开始任务
    - name: config csrs interfaces  # 任务名字
      ios_l3_interfaces:  # 模块名字
        config:
          - name: "{{ item.port }}"  # 配置接口名字
            ipv4:
            - address: "{{ item.ip }}"  # 配置接口IP地址
      with_items: "{{ csr_ifs }}"  # 导入csr_ifs这个部分的配置内容
      when: (item.router == inventory_hostname)  # 条件判断，当IP地址等于router的IP

    - name: up csrs interfaces  # 任务名字
      ios_interfaces:  # 模块名字
        config:
          - name: "{{ item.port }}"  # 配置接口名字
            enabled: True  # no shutdown
      with_items: "{{ csr_ifs }}"  # 导入csr_ifs这个部分的配置内容
      when: (item.router == inventory_hostname)  # 条件判断，当IP地址等于router的IP

    - name: csrs ospf router-id  # 任务名字
      ios_config:  # 模块名字
        lines:
          - router-id {{ item.routerid }}  # 在router配置模式,配置路由器ospf的router-id
        parents: router ospf 1  # 通过配置router ospf 1 进入router配置模式  
      with_items: "{{ csr_ospf_router_id }}"  # 导入csr_ospf_router_id这个部分的配置内容
      when: (item.router == inventory_hostname)  # 条件判断，当IP地址等于router的IP

    - name: csrs ospf network  # 任务名字
      ios_config:  # 模块名字
        lines:
          - network {{ item.network }} {{ item.mask }} area {{ item.area }}  # 网络宣告
        parents: router ospf 1  # 通过配置router ospf 1 进入router配置模式
      with_items: "{{ csr_ospf_nets }}"  # 导入csr_ospf_nets这个部分的配置内容
      when: (item.router == inventory_hostname)  # 条件判断，当IP地址等于router的IP

    - name: csrs SNMP  # 任务名字
      ios_config:  # 模块名字
        lines:
          - snmp-server community qytangro RO  # 配置只读COMMUNITY
          - snmp-server community qytangrw RW  # 配置读写COMMUNITY
          - snmp-server location BJQYT  # 配置地点
          - snmp-server contact cq_bomb  # 配置联系人
      with_items: "{{ csr_ospf_nets }}"  # 导入csr_ospf_nets这个部分的配置内容
      when: (item.router == inventory_hostname)  # 条件判断，当IP地址等于router的IP

    - name: SAVE CSRS CONFIG  # 任务名字
      ios_config:  # 模块名字
        backup: yes  # 是否备份
        save_when: modified  # 当配置修改就保存配置

- hosts: ASA  # playbook操作的设备
  gather_facts: false  # 并不收集这些主机的信息
  connection: local  # 本地发起连接
  vars_files:
    - customer_config.yaml  # 导入配置信息文件

  tasks:
    - name: config asa interfaces  # 任务名字
      asa_config:  # 模块名字
        lines:
          - ip address {{ item.ip }} {{ item.mask }}  # 配置IP地址
          - nameif {{ item.nameif }}  # 配置nameif
          - no shutdown  # 打开接口
        parents: interface {{ item.port }}  # 进入特定接口的接口配置模式
      with_items: "{{ asa_ifs }}"  # 导入asa_ifs这个部分的配置内容

    - name: config asa default route  # 任务名字
      asa_config:  # 模块名字
        lines:
          - route outside 0 0 202.100.1.1  # 配置默认路由

    - name: config static nat  # 任务名字
      asa_config:  # 模块名字
        lines:
          - host {{ item.src_host }}  # object的主机IP地址
          # 配置Static PAT转换
          - nat ({{ item.src_if }},{{ item.dst_if }}) static {{ item.dst_host }} service {{ item.protocol }} {{ item.src_port }}  {{ item.dst_port }} 
        parents: object network {{ item.host_name }}  # 创建network类型的object
      with_items: "{{ asa_nat_hosts }}"  # 导入asa_nat_hosts这个部分的配置内容

    - name: config asa acl  # 任务名字
      asa_config:  # 模块名字
        lines:
          # 配置ACE,放行访问服务器的流量
          - access-list outside_control extended permit {{ item.protocol }} any object {{ item.host_name }} eq {{ item.src_port }}
        before: clear configure access-list  # 清除之前配置的ACL
      with_items: "{{ asa_nat_hosts }}"  # 导入asa_nat_hosts这个部分的配置内容

    - name: config access-group  # 任务名字
      asa_config:  # 模块名字
        lines:
          - access-group outside_control in interface Outside  # 配置access-group

    - name: config ASA SNMP  # 任务名字
      asa_config:  # 模块名字
        lines:
          - snmp-server host MGMT 192.168.1.100 community qytangro version 2c  # 访问控制策略
          - snmp-server host MGMT 192.168.1.200 community qytangro version 2c  # 访问控制策略          
          - snmp-server location BJQYT  # 配置地点
          - snmp-server contact cq_bomb  # 配置联系人
          - snmp-server community qytangro  # 配置只读COMMUNITY(ASA只支持只读)

    - name: config ASA Syslog  # 任务名字
      asa_config:  # 模块名字
        lines:
          - logging enable  # 激活日志
          - logging trap debugging  # 发送所有日志到Syslog服务器        
          - logging host MGMT 192.168.1.100  # Syslog服务器位于MGMT接口,地址为192.168.1.100

    - name: SAVE ASA CONFIG  # 任务名字
      asa_config:  # 模块名字
        backup: yes  # 是否备份
        save: yes  # 存盘
...