csr1:
    groups:
        - cisco_ios
    hostname: 192.168.1.1
    data:
        site: beijing
        type: router
        router_id: 1.1.1.1
        ospf_process_id: 1
        interface_list:
            -   interface_name: Loopback0
                ipaddr: 1.1.1.1
                netmask: 255.255.255.255
            -   interface_name: GigabitEthernet1
                ipaddr: 137.78.5.254
                netmask: 255.255.255.0
            -   interface_name: GigabitEthernet2
                ipaddr: 61.128.1.254
                netmask: 255.255.255.0
        ospf_network_list:
            -   network: 137.78.5.0
                wildmask: 0.0.0.255
                area: 0
            -   network: 61.128.1.0
                wildmask: 0.0.0.255
                area: 0

csr2:
    groups:
        - cisco_ios
    hostname: 192.168.1.2
    data:
        site: shanghai
        type: router
        router_id: 2.2.2.2
        ospf_process_id: 1
        interface_list:
            -   interface_name: Loopback0
                ipaddr: 2.2.2.2
                netmask: 255.255.255.255
            -   interface_name: GigabitEthernet1
                ipaddr: 61.128.1.1
                netmask: 255.255.255.0
            -   interface_name: GigabitEthernet2
                ipaddr: 202.100.1.1
                netmask: 255.255.255.0
        ospf_network_list:
            -   network: 61.128.1.0
                wildmask: 0.0.0.255
                area: 0
            -   network: 202.100.1.0
                wildmask: 0.0.0.255
                area: 0

asa1:
    groups:
        - cisco_asa
    hostname: 192.168.1.3
    connection_options: #  不同的connection_type相关的参数(与netmiko参数相同)，例如:cisco_asa的secret
        netmiko:
            extras:
                secret: #  secret密码部分需要提前准备
    data:
        site: beijing
        type: firewall
        interface_list:
            -   interface_name: GigabitEthernet0/0
                ipaddr: 202.100.1.254
                netmask: 255.255.255.0
                nameif: Outside
                security_lvl: 0
            -   interface_name: GigabitEthernet0/1
                ipaddr: 10.1.1.254
                netmask: 255.255.255.0
                nameif: Inside
                security_lvl: 100
        route_list:
            -   dest: 0.0.0.0 0.0.0.0
                next_hop: 202.100.1.1
                output_if: Outside
        object_list:
            -   name: Apache
                obj_type: network
                network_type: host
                network_value: 10.1.1.100
                protocol: tcp
                src_port: 80
                dst_port: 80
                src_if: Inside
                dst_if: Outside
                nated_address: 202.100.1.100
        snmp_location: BJQYT
        snmp_contact: cq_bomb
        snmp_ro_community: qytangro
        snmp_server_list:
            -   output_if: MGMT
                snmp_server: 192.168.1.100
                community: qytangro
                version: 2c
            -   output_if: MGMT
                snmp_server: 192.168.1.200
                community: qytangro
                version: 2c
        logging_enable: true
        logging_trap: debugging
        logging_host_list:
            -   output_if: MGMT
                syslog_server: 192.168.1.100
